### ISSUE TITLE
how to fix this...

### ISSUE THREAD

**Issue by yuzki2** [BepInEx/Il2CppInterop#21]
Always when I use bepinex the unhollower doesn't work
But When I use the original(https://github.com/knah/Il2CppAssemblyUnhollower), it works without any problems

MetadataInitForMethodFileOffset =
(IntPtr)((long)XrefScannerLowLevel.JumpTargets((IntPtr)(gameAssemblyBase + unityObjectCctor.ExtractOffset())).First());

I am a beginner in programming, and I have not understood anything other than that the result of MetadataInitForMethodFileOffset is 0
I've been trying to compare it to the original, but I haven't been able to figure out what's wrong for days. Please help

[LogOutput.log](https://github.com/BepInEx/Il2CppAssemblyUnhollower/files/7771666/LogOutput.log)

**Comment by ghorsington** [comment]
Both BepInEx and unhollower have been since updated heavily (including some changes to xref scanning), and without extra info (specific game, method that is being accessed) it's difficult to tell. The issue may have been fixed, so I'm closing this for the time being until the same can be replicated with the latest BepInEx builds. Feel free to create a new issue or comment here with code specific examples if the issue still persists.
