### ISSUE TITLE
Use available assemblies where possible

### ISSUE THREAD

**Issue by KieranFoot** [BepInEx/Il2CppInterop#23]
Would it be possible to supply assemblies, say from a server build of the same project to provide missing types from the IL2CPP output?

**Comment by ghorsington** [comment]
Greetings!

Sorry for the late reply. As a side-note, this Il2CppUnhollower fork has since been rebranded into Il2CppInterop, with some of the API having been changed. Nevertheless, the answer applies to the legacy fork code and the new API.

You can supply the original managed assemblies to generate unhollowed assemblies. In the original unhollower, you can provide the paths to the generator via `UnhollowerOptions.UnityBaseLibsDir`. Note that Unhollower allows only specifying unity base library assemblies for restoring missing methods and types. There is `UnhollowerOptions.SystemLibrariesPath`, but it's only used for getting references for `mscorlib` and not restoring removed methods.

For Il2CppInterop, this same option is named `GeneratorOptions.UnityBaseLibsDir` which is passed to the [generator runner](https://github.com/BepInEx/Il2CppInterop/blob/master/Documentation/Integration-API.md#generating-proxy-assemblies-in-loaders). 

That being said, you don't need to build any separate projects and instead use [BepInEx Unity library repository](https://unity.bepinex.dev/) to download Unity base libraries for the game version you want.
